# Generated by Django 4.2.6 on 2023-10-30 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=250)),
                ('short_url', models.CharField(blank=True, max_length=15, unique=True)),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Analytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicks', models.PositiveIntegerField(default=0)),
                ('country', models.CharField(blank=True, max_length=250, null=True)),
                ('country_code', models.CharField(blank=True, max_length=250, null=True)),
                ('region_name', models.CharField(blank=True, max_length=250, null=True)),
                ('city_name', models.CharField(blank=True, max_length=250, null=True)),
                ('latitude', models.CharField(blank=True, max_length=250, null=True)),
                ('longitude', models.CharField(blank=True, max_length=250, null=True)),
                ('ip_address', models.CharField(blank=True, max_length=250, null=True)),
                ('net_provider', models.CharField(blank=True, max_length=250, null=True)),
                ('net_provider_code', models.CharField(blank=True, max_length=250, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=250, null=True)),
                ('time_zone', models.CharField(blank=True, max_length=250, null=True)),
                ('browser', models.CharField(blank=True, max_length=250, null=True)),
                ('browser_version', models.CharField(blank=True, max_length=250, null=True)),
                ('platform', models.CharField(blank=True, max_length=250, null=True)),
                ('platform_version', models.CharField(blank=True, max_length=250, null=True)),
                ('os', models.CharField(blank=True, max_length=250, null=True)),
                ('os_version', models.CharField(blank=True, max_length=250, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('short_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortener.url')),
            ],
        ),
    ]
