# Generated by Django 4.2.6 on 2023-11-01 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0002_remove_analytics_clicks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='shortener/qr_codes'),
        ),
    ]
