# Generated by Django 4.2.6 on 2023-11-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0004_alter_analytics_short_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analytics',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='latitude',
            field=models.FloatField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='analytics',
            name='longitude',
            field=models.FloatField(blank=True, max_length=250, null=True),
        ),
    ]
